name: Run CMake

on: push

jobs:
  configure:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        path: master
    - run: |
        cmake --version
    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake ../master
    - name: Read config.h
      id: config_h
      uses: juliangruber/read-file-action@v1
      with:
        path: build/config.h
    - name: Echo config.h
      run: echo ${{ steps.config_h.outputs.content }}

