name: Run CMake

on: push

jobs:
  configure:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        path: master
    - name: CMake version
      shell: bash
      run: |
        mkdir -p build
        cmake --version
    - name: Run configure
      shell: bash
      run: (cd build; cmake ../master)
    - name: Show result
      shell: bash
      run: cat build/config.h

